name: Publish to GitHub Packages

on:
  push:
    branches:
      - main   # Ändere dies, falls du einen anderen Branch verwendest, z.B. "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --settings .github/maven/settings.xml

      - name: Publish to GitHub Packages
        run: mvn deploy --settings .github/maven/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}